### ISSUE TITLE
Scroll speed not changed in OS X 10.13.1

### ISSUE THREAD

**Issue by yousifa** [pravdomil/FixSketchTrackpadSpeed#1]
It works fine on my mac 10.12.6, it does not work on my friend's mac with the same sketch app but using MacOs 10.13.1

**Comment by pravdomil** [comment]
go to Console app and search FixSketchTrackpadSpeed

<img width="1294" alt="console" src="https://user-images.githubusercontent.com/2387356/33515978-c34a15ac-d76a-11e7-9919-043e2c34aeb3.png">

**Comment by yousifa** [comment]
Nothing comes up
![screen shot 2017-12-03 at 11 43 12 pm](https://user-images.githubusercontent.com/6870090/33541445-09c13b86-d884-11e7-9e16-8874b25522b7.png)

**Comment by pravdomil** [comment]
that means that plugin is not launched
make sure that plugin is listed in sketch > settings > plugins and is active

**Comment by yousifa** [comment]
It is active there. For some reason it is not running

**Comment by yousifa** [comment]
Update: I found it in the console by typing "FixSketch", for some reason the full name doesn't find it. It is running, but on his version of OS X (10.13.1), it does not fix the scroll speed for an external mouse, only on the trackpad. On my version (10.12.6), it fixes it for both trackpad and external mouse.

**Comment by pravdomil** [comment]
Sorry, this plugin is intended for trackpad only
